---
name: 'Manual dispatch'
'on':
  workflow_dispatch:
    inputs:
      target:
        description: "Ref to retrieve"

jobs:
  display-ref:
    name: "Display currently used ref"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display target and ref
        env:
          INPUT_TARGET: ${{ github.events.inputs.target }}
          REFERENCE: ${{ github.ref_name }}
        run: |
          echo "Input target is $INPUT_TARGET"
          echo "Github reference is $REFERENCE"
          echo "hard-coded reference (new-branch)"
          cat current-version
